/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Budget {
  'expenses' : number,
  'goals' : string,
  'netIncome' : number,
}
export interface DateOfBirth {
  'day' : bigint,
  'month' : bigint,
  'year' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FullProfile {
  'privateDetails' : [] | [PrivateProfile],
  'publicProfile' : PublicProfile,
}
export interface HouseholdInvite {
  'status' : { 'pending' : null } |
    { 'accepted' : null } |
    { 'declined' : null },
  'inviterUsername' : string,
  'invitee' : Principal,
  'inviter' : Principal,
  'createdAt' : Time,
  'inviteeUsername' : string,
}
export interface PrivateProfile {
  'dob' : DateOfBirth,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'fullName' : string,
  'isAdult' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export interface PublicProfile {
  'username' : string,
  'avatar' : [] | [ExternalBlob],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptHouseholdInvite' : ActorMethod<[string], string>,
  'allUsernames' : ActorMethod<[], Array<string>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProfile' : ActorMethod<[string, string, DateOfBirth], PublicProfile>,
  'declineHouseholdInvite' : ActorMethod<[string], undefined>,
  'getAllProfilesByUsername' : ActorMethod<[], Array<[string, PublicProfile]>>,
  'getAllPublicProfiles' : ActorMethod<[], Array<PublicProfile>>,
  'getAllUsersAsStaff' : ActorMethod<
    [],
    Array<[string, PublicProfile, [] | [PrivateProfile]]>
  >,
  'getAvatar' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getBudgetByUsername' : ActorMethod<[string], [] | [Budget]>,
  'getCallerUserProfile' : ActorMethod<[], FullProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingInvites' : ActorMethod<[], Array<[string, HouseholdInvite]>>,
  'getPersonalBudget' : ActorMethod<[], [] | [Budget]>,
  'getPrivateProfileAsStaff' : ActorMethod<[Principal], [] | [PrivateProfile]>,
  'getPublicProfile' : ActorMethod<[string], PublicProfile>,
  'getUserProfile' : ActorMethod<[Principal], FullProfile>,
  'inviteToHousehold' : ActorMethod<[string], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, DateOfBirth], undefined>,
  'savePersonalBudget' : ActorMethod<[Budget], undefined>,
  'uploadProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];