/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DateOfBirth = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PublicProfile = IDL.Record({
  'username' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const PrivateProfile = IDL.Record({
  'dob' : DateOfBirth,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'fullName' : IDL.Text,
  'isAdult' : IDL.Bool,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Budget = IDL.Record({
  'expenses' : IDL.Float64,
  'goals' : IDL.Text,
  'netIncome' : IDL.Float64,
});
export const FullProfile = IDL.Record({
  'privateDetails' : IDL.Opt(PrivateProfile),
  'publicProfile' : PublicProfile,
});
export const HouseholdInvite = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  }),
  'inviterUsername' : IDL.Text,
  'invitee' : IDL.Principal,
  'inviter' : IDL.Principal,
  'createdAt' : Time,
  'inviteeUsername' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptHouseholdInvite' : IDL.Func([IDL.Text], [IDL.Text], []),
  'allUsernames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, DateOfBirth],
      [PublicProfile],
      [],
    ),
  'declineHouseholdInvite' : IDL.Func([IDL.Text], [], []),
  'getAllProfilesByUsername' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PublicProfile))],
      ['query'],
    ),
  'getAllPublicProfiles' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
  'getAllUsersAsStaff' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PublicProfile, IDL.Opt(PrivateProfile)))],
      ['query'],
    ),
  'getAvatar' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getBudgetByUsername' : IDL.Func([IDL.Text], [IDL.Opt(Budget)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [FullProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingInvites' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, HouseholdInvite))],
      ['query'],
    ),
  'getPersonalBudget' : IDL.Func([], [IDL.Opt(Budget)], ['query']),
  'getPrivateProfileAsStaff' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PrivateProfile)],
      ['query'],
    ),
  'getPublicProfile' : IDL.Func([IDL.Text], [PublicProfile], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [FullProfile], ['query']),
  'inviteToHousehold' : IDL.Func([IDL.Text], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, DateOfBirth], [], []),
  'savePersonalBudget' : IDL.Func([Budget], [], []),
  'uploadProfilePicture' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DateOfBirth = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PublicProfile = IDL.Record({
    'username' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const PrivateProfile = IDL.Record({
    'dob' : DateOfBirth,
    'createdAt' : Time,
    'lastUpdated' : Time,
    'fullName' : IDL.Text,
    'isAdult' : IDL.Bool,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Budget = IDL.Record({
    'expenses' : IDL.Float64,
    'goals' : IDL.Text,
    'netIncome' : IDL.Float64,
  });
  const FullProfile = IDL.Record({
    'privateDetails' : IDL.Opt(PrivateProfile),
    'publicProfile' : PublicProfile,
  });
  const HouseholdInvite = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'accepted' : IDL.Null,
      'declined' : IDL.Null,
    }),
    'inviterUsername' : IDL.Text,
    'invitee' : IDL.Principal,
    'inviter' : IDL.Principal,
    'createdAt' : Time,
    'inviteeUsername' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptHouseholdInvite' : IDL.Func([IDL.Text], [IDL.Text], []),
    'allUsernames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, DateOfBirth],
        [PublicProfile],
        [],
      ),
    'declineHouseholdInvite' : IDL.Func([IDL.Text], [], []),
    'getAllProfilesByUsername' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PublicProfile))],
        ['query'],
      ),
    'getAllPublicProfiles' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
    'getAllUsersAsStaff' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PublicProfile, IDL.Opt(PrivateProfile)))],
        ['query'],
      ),
    'getAvatar' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getBudgetByUsername' : IDL.Func([IDL.Text], [IDL.Opt(Budget)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [FullProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingInvites' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, HouseholdInvite))],
        ['query'],
      ),
    'getPersonalBudget' : IDL.Func([], [IDL.Opt(Budget)], ['query']),
    'getPrivateProfileAsStaff' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PrivateProfile)],
        ['query'],
      ),
    'getPublicProfile' : IDL.Func([IDL.Text], [PublicProfile], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [FullProfile], ['query']),
    'inviteToHousehold' : IDL.Func([IDL.Text], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, DateOfBirth], [], []),
    'savePersonalBudget' : IDL.Func([Budget], [], []),
    'uploadProfilePicture' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };